#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────
# MiroShark — local Ollama stack setup (idempotent)
#
# Reproduces the free, local setup (Ollama + Neo4j + nomic embeddings) on a
# fresh machine. Safe to re-run: it NEVER overwrites an existing .env /
# frontend/.env.local, and keeps the backend↔frontend internal key in sync.
#
#   bash scripts/local_setup.sh                # config + models + deps
#   bash scripts/local_setup.sh --neo4j-docker # also start a Neo4j container
#   bash scripts/local_setup.sh --no-deps      # skip npm/uv install
#   bash scripts/local_setup.sh --no-models    # skip ollama pulls
#
# Overridable:
#   MIROSHARK_LLM_MODEL   (default qwen2.5:7b — instruct-tuned, does NER JSON)
#   MIROSHARK_EMBED_MODEL (default nomic-embed-text)
#   NEO4J_PASSWORD        (default miroshark)
# ──────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

LLM_MODEL="${MIROSHARK_LLM_MODEL:-qwen2.5:7b}"
EMBED_MODEL="${MIROSHARK_EMBED_MODEL:-nomic-embed-text}"
NEO4J_PASS="${NEO4J_PASSWORD:-miroshark}"

DO_DEPS=1; DO_MODELS=1; DO_NEO4J_DOCKER=0
for a in "$@"; do case "$a" in
  --no-deps) DO_DEPS=0 ;;
  --no-models) DO_MODELS=0 ;;
  --neo4j-docker) DO_NEO4J_DOCKER=1 ;;
  -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
  *) echo "unknown arg: $a" >&2; exit 2 ;;
esac; done

if [[ -t 1 ]]; then
  GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; BOLD='\033[1m'; RESET='\033[0m'
else GREEN='' YELLOW='' CYAN='' RED='' BOLD='' RESET=''; fi
info()    { printf "${CYAN}  [*]${RESET} %s\n" "$*"; }
success() { printf "${GREEN}  [+]${RESET} %s\n" "$*"; }
warn()    { printf "${YELLOW}  [!]${RESET} %s\n" "$*"; }
error()   { printf "${RED}  [-]${RESET} %s\n" "$*"; }
header()  { printf "\n${BOLD}  === %s ===${RESET}\n\n" "$*"; }

gen_key() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  elif command -v python3 >/dev/null 2>&1; then python3 -c 'import secrets;print(secrets.token_hex(32))'
  else error "need openssl or python3 to generate a key"; exit 1; fi
}

# ── 1. Prerequisites ──────────────────────────────────────
header "Prerequisites"
for tool in node npm; do
  command -v "$tool" >/dev/null 2>&1 && success "$tool: $(command -v "$tool")" || { error "$tool missing — install Node >=18"; exit 1; }
done
command -v uv >/dev/null 2>&1 && success "uv: $(command -v uv)" || warn "uv missing — backend deps need it (https://docs.astral.sh/uv/)"
command -v ollama >/dev/null 2>&1 && success "ollama: $(command -v ollama)" || warn "ollama missing — LLM/embeddings need it (https://ollama.com)"

# ── 2. Backend .env (create only if absent; never overwrite) ──
header "Backend config (.env)"
if [[ -f .env ]]; then
  KEY="$(grep -E '^MIROSHARK_INTERNAL_KEY=' .env | head -1 | cut -d= -f2- | tr -d '[:space:]' || true)"
  if [[ -z "$KEY" || "$KEY" == PASTE_* ]]; then
    warn ".env exists but MIROSHARK_INTERNAL_KEY is empty/placeholder — set it, then re-run for frontend sync"
    KEY=""
  else
    success ".env present — keeping it (reusing its internal key)"
  fi
else
  KEY="$(gen_key)"
  cat > .env <<EOF
# Generated by scripts/local_setup.sh — local Ollama stack. See LOCAL_SETUP.md.
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=${NEO4J_PASS}

LLM_PROVIDER=openai
LLM_API_KEY=ollama
LLM_BASE_URL=http://localhost:11434/v1
LLM_MODEL_NAME=${LLM_MODEL}

EMBEDDING_PROVIDER=ollama
EMBEDDING_MODEL=${EMBED_MODEL}
EMBEDDING_BASE_URL=http://localhost:11434
EMBEDDING_DIMENSIONS=768

RERANKER_ENABLED=false
OLLAMA_NUM_CTX=8192
FLASK_DEBUG=true
SECRET_KEY=miroshark-local-dev
MIROSHARK_INTERNAL_KEY=${KEY}
EOF
  success "wrote .env (LLM=${LLM_MODEL}, embeddings=${EMBED_MODEL}, fresh internal key)"
fi

# ── 3. Frontend frontend/.env.local (create/sync) ──────────
header "Frontend config (frontend/.env.local)"
FE=frontend/.env.local
if [[ -f "$FE" ]]; then
  FE_KEY="$(grep -E '^VITE_INTERNAL_KEY=' "$FE" | head -1 | cut -d= -f2- | tr -d '[:space:]' || true)"
  if [[ -n "$KEY" && "$FE_KEY" != "$KEY" ]]; then
    warn "$FE exists but its VITE_INTERNAL_KEY != backend key — fix it to match, or delete it and re-run"
  else
    success "$FE present — keeping it"
  fi
elif [[ -n "$KEY" ]]; then
  cat > "$FE" <<EOF
VITE_API_BASE_URL=http://localhost:5001
VITE_INTERNAL_KEY=${KEY}
EOF
  success "wrote $FE (localhost:5001, key matched to backend)"
else
  warn "skipped $FE — no backend key available yet (set MIROSHARK_INTERNAL_KEY in .env, re-run)"
fi

# ── 4. Ollama models ──────────────────────────────────────
if [[ $DO_MODELS -eq 1 ]] && command -v ollama >/dev/null 2>&1; then
  header "Ollama models"
  have() { ollama list 2>/dev/null | awk '{print $1}' | grep -qx "$1"; }
  for m in "$LLM_MODEL" "$EMBED_MODEL"; do
    if have "$m"; then success "have $m"
    else info "pulling $m ..."; ollama pull "$m" && success "pulled $m" || warn "pull failed for $m — adjust MIROSHARK_LLM_MODEL or pull manually"; fi
  done
  warn "Do NOT use gemma4:e4b for LLM — too weak for NER (returns empty JSON -> 0 entities)."
elif [[ $DO_MODELS -eq 1 ]]; then
  warn "ollama not found — skipping model pulls"
fi

# ── 5. Neo4j ──────────────────────────────────────────────
header "Neo4j"
if nc -z localhost 7687 2>/dev/null || (command -v lsof >/dev/null 2>&1 && lsof -iTCP:7687 -sTCP:LISTEN -t >/dev/null 2>&1); then
  success "Neo4j reachable on :7687"
elif [[ $DO_NEO4J_DOCKER -eq 1 ]] && command -v docker >/dev/null 2>&1; then
  info "starting Neo4j container ..."
  docker run -d --name miroshark-neo4j -p7687:7687 -p7474:7474 \
    -e NEO4J_AUTH="neo4j/${NEO4J_PASS}" neo4j:community >/dev/null \
    && success "Neo4j container started (neo4j/${NEO4J_PASS})" || warn "docker run failed — start Neo4j yourself"
else
  warn "Neo4j not reachable on :7687 — start it (brew services start neo4j | neo4j start | --neo4j-docker)"
fi

# ── 6. Dependencies ───────────────────────────────────────
if [[ $DO_DEPS -eq 1 ]]; then
  header "Dependencies (npm + uv)"
  info "npm run setup:all ..."
  npm run setup:all && success "deps installed" || warn "setup:all failed — run it manually"
fi

# ── Done ──────────────────────────────────────────────────
header "Done"
success "Start the stack:  npm run dev    (backend :5001 + frontend :3000)"
success "Open:             http://localhost:3000  → Settings → LLM Connection Test (must be green)"
success "Headless S2S:     see docs/S2S-SCENARIO-API.md"
